### ISSUE TITLE
添加ipv6,udp会崩溃

### ISSUE THREAD

**Issue by drzazi** [csznet/goForward#11]
启动命令为：ExecStart=/usr/local/bin/goForward -pass 5GdXHEA*rwEwBTnXzbFr -port 30000
在界面添加ipv6，两个相同的端口后，工具崩溃，可复现，日志如下

`Apr 17 02:50:44 cn goForward[15293]: goForward Version v1.1.9
Apr 17 02:50:44 cn goForward[15293]: Data: /usr/local/bin/goForward.db
Apr 17 02:50:45 cn goForward[15293]: Web<E7><AE><A1><E7><90><86><E9><9D><A2><E6><9D><BF><E7><AB><AF><E5><8F><A3>:30000
Apr 17 02:50:45 cn goForward[15293]: <E3><80><90>udp<E3><80><91><E7>91><E5><90><AC><E7><AB><AF><E5><8F><A3> 30000 <E8><BD><AC><E5><8F><91><E8><87><B3> 127.0.0.1:30000
Apr 17 02:50:51 cn goForward[15293]: [GIN] 2024/04/17 - 02:50:51 | 200 |      802.27<C2><B5>s | 2001:da8:b000:6801:929c:4aff:fec1:f4db | GET      "/"
Apr 17 02:51:29 cn goForward[15293]: [GIN] 2024/04/17 - 02:51:29 | 200 |    9.659558ms | 2001:da8:b000:6801:929c:4aff:fec1:f4db | POST     "/add"
Apr 17 02:51:29 cn goForward[15293]: <E3><80><90>udp<E3><80><91><E7>91><E5><90><AC><E7><AB><AF><E5><8F><A3> 35544 <E8><BD><AC><E5><8F><91><E8><87><B3> 2401:1fe0::eef:35544
Apr 17 02:51:29 cn goForward[15293]: 2024/04/17 02:51:29 <E8><A7><A3><E6><9E><90><E8><BF><9C><E7><A8><8B><E5><9C><B0><E5><9D><80><E6><97><B6><E5><8F><91><E7><94><9F><E9><94><99>  >
Apr 17 02:51:29 cn systemd[1]: goForward.service: Main process exited, code=exited, status=1/FAILURE
Apr 17 02:51:29 cn systemd[1]: goForward.service: Failed with result 'exit-code'.`

**Comment by csznet** [comment]
是指添加ipv6的远程地址，两个远程端口都是相同的但是本地端口不相同，继而出现的错误吗

**Comment by drzazi** [comment]
> 是指添加ipv6的远程地址，两个远程端口都是相同的但是本地端口不相同，继而出现的错误吗

你好，经过测试，我发现和端口无关，转发udp ipv6发现报如下错误
2024/04/19 00:07:04 解析远程地址时发生错误: address [a ipv6 address]: too many colons in address

暂时解决方法：在web界面，如果选udp，在ipv6外面包裹[]就不再报错，但选tcp就不用包裹[]，这可能是个bug?

**Comment by drzazi** [comment]
但是我的转发依然没成功。我是在ipv6 only的机器上，转发远程ipv6+端口。按照上一条成功添加后，在转发时报错退出

报错信息如下：
`[GIN] 2024/04/19 - 00:35:57 | 200 |    1.069786ms | 2001:da8:b000:6801:929c:4aff:fec1:f4db | GET      "/"
panic: interface conversion: interface {} is *[]uint8, not []uint8

goroutine 37 [running]:
csz.net/goForward/forward.(*ConnectionStats).copyBytes(0xc00036c2d0, {0xdc89d0, 0xc000012188}, {0xdc89d0, 0xc0000121e0})
        /home/runner/work/goForward/goForward/forward/forward.go:208 +0x394
csz.net/goForward/forward.(*ConnectionStats).handleTCPConnection.func1()
        /home/runner/work/goForward/goForward/forward/forward.go:150 +0x6c
created by csz.net/goForward/forward.(*ConnectionStats).handleTCPConnection
        /home/runner/work/goForward/goForward/forward/forward.go:148 +0x395`
