### ISSUE TITLE
小白问个问题

### ISSUE THREAD

**Issue by akaagiao1** [csznet/goForward#13]
× goForward.service - Start goForward on boot
     Loaded: loaded (/etc/systemd/system/goForward.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-04-17 21:40:06 CST; 36s ago
   Duration: 10.111s
    Process: 1822 ExecStart=/root/goForward (code=exited, status=2)
   Main PID: 1822 (code=exited, status=2)
        CPU: 625ms

Apr 17 21:40:06 C20240408212180 goForward[1822]: panic: interface conversion: interface {} is *[]uint8, not []uint8
Apr 17 21:40:06 C20240408212180 goForward[1822]: goroutine 30 [running]:
Apr 17 21:40:06 C20240408212180 goForward[1822]: csz.net/goForward/forward.(*ConnectionStats).copyBytes(0xc00011c120, {0xdc89d0, 0xc0000124b8}, {0xdc89d0, 0xc0000124a0})
Apr 17 21:40:06 C20240408212180 goForward[1822]:         /home/runner/work/goForward/goForward/forward/forward.go:208 +0x394
Apr 17 21:40:06 C20240408212180 goForward[1822]: csz.net/goForward/forward.(*ConnectionStats).handleTCPConnection.func2()
Apr 17 21:40:06 C20240408212180 goForward[1822]:         /home/runner/work/goForward/goForward/forward/forward.go:154 +0x6c
Apr 17 21:40:06 C20240408212180 goForward[1822]: created by csz.net/goForward/forward.(*ConnectionStats).handleTCPConnection
Apr 17 21:40:06 C20240408212180 goForward[1822]:         /home/runner/work/goForward/goForward/forward/forward.go:152 +0x451
Apr 17 21:40:06 C20240408212180 systemd[1]: goForward.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 17 21:40:06 C20240408212180 systemd[1]: goForward.service: Failed with result 'exit-code'.
root@C20240408212180:~#

**Comment by csznet** [comment]
已在新版本修复
